<?php

namespace App\Repository;

use App\Models\Order;
use Illuminate\Database\Eloquent\ModelNotFoundException;

use App\Models\Customer;
use App\Models\Product;
use App\Models\OrderItem;

class OrdersRepository
{
    public function paginate(int $perPage = 15)
    {
        return Order::latest()->paginate($perPage);
    }

    public function create(array $payload)
    {
        // Resolve customer UUID to numeric id
    $customer = Customer::findOrFail($payload['customer_id']);
    
        // Calculate total using product_id (numeric)
        $total = 0;
        foreach ($payload['items'] as $item) {
$product = Product::where('uuid', $item['product_uuid'])->firstOrFail();
            $total += $product->price * $item['quantity'];
        }
    
        // Create order (UUID auto-generated by HasUuids)
        $order = Order::create([
            'customer_id'  => $customer->id,
            'total_amount' => $total,
        ]);
    
        // Create order items
        foreach ($payload['items'] as $item) {
            $product = Product::where('uuid', $item['product_uuid'])->firstOrFail();
    
            OrderItem::create([
                'order_id'   => $order->id,
                'product_id' => $product->id,
                'quantity'   => $item['quantity'],
                'unit_price' => $product->price,
            ]);

            // Decrement product stock
            $product->decrement('quantity', $item['quantity']);
        }
    
        // Return order with items + product relationship
        return $order->load('items.product');
    }
    
    

    public function findByUuid(string $uuid)
    {
        return Order::where('uuid', $uuid)->firstOrFail();
    }

    public function findByField(string $field, $value)
    {
        return Order::where($field, $value)->firstOrFail();
    }

    public function update(string $uuid, array $payload)
    {
        $model = $this->findByUuid($uuid);
        $model->update($payload);
        return $model;
    }

    public function delete(string $uuid)
    {
        $model = $this->findByUuid($uuid);
        return $model->delete();
    }

    public function restore(string $uuid)
    {
        $model = Order::withTrashed()->where('uuid', $uuid)->firstOrFail();
        $model->restore();
        return $model;
    }

    public function getSummary(string $from, string $to)
{
    $from = $from . ' 00:00:00';
    $to = $to . ' 23:59:59';

    $revenue = Order::whereBetween('created_at', [$from, $to])
        ->sum('total_amount');

    $customerCount = Order::whereBetween('created_at', [$from, $to])
        ->distinct('customer_id')
        ->count('customer_id');

    $topProducts = OrderItem::whereHas('order', function ($q) use ($from, $to) {
            $q->whereBetween('created_at', [$from, $to]);
        })
        ->select(
            'product_id',
            \Illuminate\Support\Facades\DB::raw('SUM(quantity) as total_quantity'),
            \Illuminate\Support\Facades\DB::raw('SUM(quantity * unit_price) as total_revenue')
        )
        ->groupBy('product_id')
        ->orderByDesc('total_quantity')
        ->limit(5)
        ->with('product')
        ->get()
        ->map(function ($item) {
            return [
                'product_id' => $item->product_id,
                'product_name' => $item->product?->name ?? 'Unknown Product',
                'total_quantity' => (int) $item->total_quantity,
                'total_revenue' => (float) $item->total_revenue,
            ];
        });

    return [
        'total_revenue' => (float) $revenue,
        'total_customers' => $customerCount,
        'top_products' => $topProducts,
    ];
}
}