<?php

namespace App\Repository;

use App\Models\Order;
use Illuminate\Database\Eloquent\ModelNotFoundException;

use App\Models\Customer;
use App\Models\Product;
use App\Models\OrderItem;

class OrdersRepository
{
    public function paginate(int $perPage = 15)
    {
        return Order::latest()->paginate($perPage);
    }

    public function create(array $payload)
    {
        // Resolve customer UUID to numeric id
        $customer = Customer::where('uuid', $payload['customer_id'])->first();
    
        // Calculate total using product_id (numeric)
        $total = 0;
        foreach ($payload['items'] as $item) {
            $product = Product::findOrFail($item['product_id']); // numeric id
            $total += $product->price * $item['quantity'];
        }
    
        // Create order (UUID auto-generated by HasUuids)
        $order = Order::create([
            'customer_id'  => $customer->id,
            'product_id' => $product->id,
            'quantity'   => $item['quantity']
        ]);
    
        // Create order items
        foreach ($payload['items'] as $item) {
            $product = Product::findOrFail($item['product_id']); // numeric id
    
            OrderItem::create([
                'order_id'   => $order->id,
                'product_id' => $product->id,
                'quantity'   => $item['quantity'],
                'unit_price' => $product->price,
                'total_amount' => $total
            ]);
        }
    
        // Return order with items + product relationship
        return $order->load('items.product');
    }
    
    

    public function findByUuid(string $uuid)
    {
        return Order::where('uuid', $uuid)->first();
    }

    public function findByField(string $field, $value)
    {
        return Order::where($field, $value)->first();
    }

    public function update(string $uuid, array $payload)
    {
        $model = $this->findByUuid($uuid);
        $model->update($payload);
        return $model;
    }

    public function delete(string $uuid)
    {
        $model = $this->findByUuid($uuid);
        return $model->delete();
    }

    public function restore(string $uuid)
    {
        $model = Order::withTrashed()->where('uuid', $uuid)->first();
        $model->restore();
        return $model;
    }
}