<?php

namespace App\Repository;

use App\Models\Order;
use Illuminate\Database\Eloquent\ModelNotFoundException;

use App\Models\Customer;
use App\Models\Product;
use App\Models\OrderItem;

class OrdersRepository
{
    public function paginate(int $perPage = 15)
    {
        return Order::latest()->paginate($perPage);
    }

    public function create(array $payload)
    {
        // Resolve customer UUID to numeric id
        $customerUuid = $payload['customer_uuid'] ?? $payload['customer_id'];
        
        // The frontend might have sent the User's UUID instead of the Customer's UUID
        $user = \App\Models\User::where('uuid', $customerUuid)->first();
        if ($user) {
            $customer = $user->customer_id ? Customer::find($user->customer_id) : null;
            
            // If the customer doesn't exist in the database (data inconsistency), create it
            if (!$customer) {
                $customer = Customer::firstOrCreate(
                    ['email' => $user->email],
                    ['name' => $user->name]
                );
                $user->update(['customer_id' => $customer->id]);
            }
        } else {
            $customer = Customer::where('uuid', $customerUuid)->firstOrFail();
        }
    
        // Calculate total using product
        $total = 0;
        foreach ($payload['items'] as $item) {
            $productUuid = $item['product_uuid'] ?? $item['product_id'];
            $product = Product::where('uuid', $productUuid)->firstOrFail();
            $total += $product->price * $item['quantity'];
        }
    
        // Create order (UUID auto-generated by HasUuids)
        $order = Order::create([
            'customer_id'  => $customer->id,
            'total_amount' => $total,
        ]);
    
        // Create order items
        foreach ($payload['items'] as $item) {
            $productUuid = $item['product_uuid'] ?? $item['product_id'];
            $product = Product::where('uuid', $productUuid)->firstOrFail();
    
            OrderItem::create([
                'order_id'   => $order->id,
                'product_id' => $product->id,
                'quantity'   => $item['quantity'],
                'unit_price' => $product->price,
            ]);
        }
    
        // Return order with items + product relationship
        return $order->load('items.product');
    }
    
    

    public function findByUuid(string $uuid)
    {
        return Order::where('uuid', $uuid)->firstOrFail();
    }

    public function findByField(string $field, $value)
    {
        return Order::where($field, $value)->firstOrFail();
    }

    public function update(string $uuid, array $payload)
    {
        $model = $this->findByUuid($uuid);
        $model->update($payload);
        return $model;
    }

    public function delete(string $uuid)
    {
        $model = $this->findByUuid($uuid);
        return $model->delete();
    }

    public function restore(string $uuid)
    {
        $model = Order::withTrashed()->where('uuid', $uuid)->firstOrFail();
        $model->restore();
        return $model;
    }
}