<?php

namespace App\Repository;

use App\Models\Order;
use Illuminate\Database\Eloquent\ModelNotFoundException;

use App\Models\Customer;
use App\Models\Product;
use App\Models\OrderItem;

class OrdersRepository
{
    public function paginate(int $perPage = 15)
    {
        return Order::latest()->paginate($perPage);
    }

   public function create(array $payload)
{
    // Resolve customer UUID to numeric id
    $customer = Customer::where('uuid', $payload['customer_id'])->firstOrFail();

    // Calculate total using product_uuid
    $total = 0;
    foreach ($payload['items'] as $item) {
        $product = Product::where('uuid', $item['product_uuid'])->firstOrFail();
        $total += $product->price * $item['quantity'];
    }

    // Create order (UUID auto-generated by HasUuids)
    $order = Order::create([
        'customer_id'  => $customer->id,   // still store numeric ID internally
        'total_amount' => $total,
    ]);

    // Create order items
    foreach ($payload['items'] as $item) {
        $product = Product::where('uuid', $item['product_uuid'])->firstOrFail();

        OrderItem::create([
            'order_id'   => $order->id,
            'product_id' => $product->id,   // numeric ID stored in order_items
            'quantity'   => $item['quantity'],
            'unit_price' => $product->price,
        ]);
    }

    // Return order with items + product relationship
    return $order->load('items.product');
}

    

    public function findByUuid(string $uuid)
    {
        return Order::where('uuid', $uuid)->firstOrFail();
    }

    public function findByField(string $field, $value)
    {
        return Order::where($field, $value)->firstOrFail();
    }

    public function update(string $uuid, array $payload)
    {
        $model = $this->findByUuid($uuid);
        $model->update($payload);
        return $model;
    }

    public function delete(string $uuid)
    {
        $model = $this->findByUuid($uuid);
        return $model->delete();
    }

    public function restore(string $uuid)
    {
        $model = Order::withTrashed()->where('uuid', $uuid)->firstOrFail();
        $model->restore();
        return $model;
    }
}